version: "3.8"

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app # Mount current dir into container
      - /app/node_modules # Prevent host from overwriting node_modules
    networks:
      - app-network
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/mydatabase

networks:
  app-network:

volumes:
  mongo-data:
